`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: XAUT_IC
// Engineer: CBX1997
// 
// Create Date: 2020/07/29 21:30:27
// Design Name: 
// Module Name: forever_tb
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: The clock module generated by the forever statement
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module forever_tb ;
			reg clock;
			initial
			 			begin
			 				clock <=0;
			 				forever #50clock  <= ~clock;
			 			end			 				
endmodule
